<?php

/**
 * Implements hook_bean_types_api_info().
 */
function bean_mapboxjs_bean_types_api_info() {
  return array('api' => 4);
}

/**
 * Implements hook_bean_types().
 */
function bean_mapboxjs_bean_types() {
  $plugins = array();
  $plugins['bean_mapboxjs'] = array(
    'label' => t('Mapbox Map'),
    'description' => t('A MapBox map rendered with MapBox.js.'),
    'handler' => array(
      'class' => 'BeansMapboxjs',
      'parent' => 'bean',
      'path' => drupal_get_path('module', 'bean_mapbosjs') . '/plugins/bean',
      'file' => 'bean_mapboxjs.inc',
    ),
  );
  return $plugins;
}
