<?php

/**
 * Implements hook_requirements().
 */
function mapboxjs_requirements($phase) {
  $requirements = array();

  // ensure js library is available
  if ($phase == 'runtime' && !file_exists(libraries_get_path('mapboxjs') . '/mapbox.js')) {
    $requirements['mapboxjss'] = array(
      'title' => t('MapBox.js library not found'),
      'value' => t('The !mapboxjs javascript library was not found. Please !download it into the mapbox subdirectory of the libraries folder.',
        array(
          '!mapboxjs' => l('MapBox.js', 'http://mapbox.com/mapbox.js'),
          '!download' => l('download', 'http://api.tiles.mapbox.com/mapbox.js/v0.6.6/mapbox.js'),
        )
      ),
      'severity' => REQUIREMENT_ERROR,
    );
  }
    // ensure MapBox css file is available
  if ($phase == 'runtime' && !file_exists(libraries_get_path('mapboxjs') . '/mapbox.css')) {
    $requirements['mapboxjs'] = array(
      'title' => t('MapBox css not found'),
      'value' => t('The !mapboxjs css file was not found. Please !download it into the mapbox subdirectory of the libraries folder.',
        array(
          '!mapboxjs' => l('MapBox.js', 'http://mapbox.com/mapbox.js'),
          '!download' => l('download', 'http://api.tiles.mapbox.com/mapbox.js/v0.6.6/mapbox.css'),
        )
      ),
      'severity' => REQUIREMENT_ERROR,
    );
  }

  return $requirements;
}

/**
 * Implements hook_library().
 */
function mapboxjs_library() {
  $libraries['mapboxjs'] = array(
    'title' => 'MapBox.js',
    'website' => 'http://mapbox.com/mapbox.js',
    'version' => '0.6.6',
    'js' => array(
      libraries_get_path('mapboxjs') . '/mapbox.js' => array(
        'type' => 'file',
      ),
    ),
    'css' => array(
      libraries_get_path('mapboxjs') . '/mapbox.css' => array(
        'type' => 'file',
        'media' => 'screen',
        'group' => CSS_DEFAULT,
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_theme().
 */
function mapboxjs_theme($existing, $type, $theme, $path) {
  return array(
    'mapboxjs_map' => array(
      'arguments' => array('map_id' => NULL, 'height' => '400px'),
      'template' => 'mapboxjs_map',
    ),
  );
}

/**
 * Load all MapBox.js required client files and return markup for a map.
 *
 * @param string $map_id
 * @param string $height
 *
 * @return string map markup
 */
function mapboxjs_render_map($map_id = 'mapboxjs-map', $height = '400px') {
  // Add javascript and css dependencies.
  drupal_add_library('mapboxjs', 'mapboxjs');
  return theme('mapboxjs_map', array('map_id' => $map_id, 'height' => $height));
}
