<?php

/**
 * Implements hook_block_info().
 */
function mapboxjs_block_block_info() {
  // Get all of our MapBox.js map preset objects.
  $presets = mapboxjs_load_presets();
  $blocks = array();
  foreach ($presets as $preset) {
    $blocks[$preset->name] = array(
      'info' => t('MapBox map: @label', array('@label' => $preset->label))
    );
  }

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function mapboxjs_block_block_view($delta = '') {
  $block = array();

  $preset = mapboxjs_load_presets($delta);
  $block['subject'] = $preset->label;
  $block['content'] = mapboxjs_render_preset($preset);

  return $block;
}
